name: _
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - pkgs/http
  - pkgs/http_client_conformance_tests
  - pkgs/http_multi_server
  - pkgs/http_parser
  - pkgs/http_profile
  - pkgs/http2
  - pkgs/ok_http
  - pkgs/web_socket
  - pkgs/web_socket_channel
  - pkgs/web_socket_conformance_tests
