sdk:
- pubspec
- dev

stages:
- analyze_and_format:
  - analyze: --fatal-infos
  - format:
    sdk:
    - dev
- unit_test:
  - test: --test-randomize-ordering-seed=random --platform vm
    os:
    - linux
  - test: --test-randomize-ordering-seed=random --platform chrome
    os:
    - linux
  - test: --test-randomize-ordering-seed=random --platform firefox
    os:
    - linux
  - command: dart run --define=no_default_http_client=true test/no_default_http_client_test.dart
    os:
    - linux
  - test: --test-randomize-ordering-seed=random -p chrome -c dart2wasm
    sdk: dev
