name: package:cronet_http CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/cronet.yml'
      - 'pkgs/cronet_http/**'
      - 'pkgs/http_client_conformance_tests/**'
  pull_request:
    paths:
      - '.github/workflows/cronet.yml'
      - 'pkgs/cronet_http/**'
      - 'pkgs/http_client_conformance_tests/**'
  schedule:
    - cron: "0 0 * * 0"

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  verify:
    name: Format & Analyze & Test
    runs-on: ubuntu-cpu16-ram64
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        cronetHttpNoPlay: ['false', 'true']
    defaults:
      run:
        working-directory: pkgs/cronet_http
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046
        with:
          channel: 'stable'
      - id: install
        name: Install dependencies
        run: flutter pub get
      - name: Check formatting
        if: always() && steps.install.outcome == 'success'
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze code
        if: always() && steps.install.outcome == 'success'
        run: flutter analyze --fatal-infos
      - run: cd example && flutter build apk && cd ..
      - run: sed -i 's/0.12.0/0.14.2/' pubspec.yaml
      - run: dart run jnigen --config jnigen.yaml
      - run: git diff