name: Dart Health
on:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/dart_health.yml'
      - 'pkgs/http/**'
      - 'pkgs/http_client_conformance_tests/**'
      - 'pkgs/http_parser/**'
      - 'pkgs/http_profile/**'
      - 'pkgs/http2/**'
      - 'pkgs/web_socket/**'
      - 'pkgs/web_socket_conformance_tests/**'
  pull_request:
    paths:
      - '.github/workflows/dart_health.yml'
      - 'pkgs/http/**'
      - 'pkgs/http_client_conformance_tests/**'
      - 'pkgs/http_parser/**'
      - 'pkgs/http_profile/**'
      - 'pkgs/http2/**'
      - 'pkgs/web_socket/**'
      - 'pkgs/web_socket_conformance_tests/**'

jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@main
    with:
      sdk: master
      ignore_packages: 'pkgs/cronet_http,pkgs/cupertino_http,pkgs/flutter_http_example,pkgs/java_http,pkgs/ok_http'
    permissions:
      pull-requests: write
